// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBDIg1187qM0vCZ6pneB1pOnJqEKbV6qro',
    appId: '1:82640420733:web:4474bb4721cdb22f4e1614',
    messagingSenderId: '82640420733',
    projectId: 'better-brain-7231d',
    authDomain: 'better-brain-7231d.firebaseapp.com',
    storageBucket: 'better-brain-7231d.firebasestorage.app',
    measurementId: 'G-G9JCETXHB3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAWUv9JPwtbRXLNIl4r2rq250YkBqAP4Jg',
    appId: '1:82640420733:android:da6ba66fe8f748874e1614',
    messagingSenderId: '82640420733',
    projectId: 'better-brain-7231d',
    storageBucket: 'better-brain-7231d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDXl_pdTqdgXhTNRko7cVF-moft7t4zIEg',
    appId: '1:82640420733:ios:606b189b7a245c074e1614',
    messagingSenderId: '82640420733',
    projectId: 'better-brain-7231d',
    storageBucket: 'better-brain-7231d.firebasestorage.app',
    iosBundleId: 'com.example.betterBrain',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDXl_pdTqdgXhTNRko7cVF-moft7t4zIEg',
    appId: '1:82640420733:ios:606b189b7a245c074e1614',
    messagingSenderId: '82640420733',
    projectId: 'better-brain-7231d',
    storageBucket: 'better-brain-7231d.firebasestorage.app',
    iosBundleId: 'com.example.betterBrain',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBDIg1187qM0vCZ6pneB1pOnJqEKbV6qro',
    appId: '1:82640420733:web:e0f0bbc4f254f8964e1614',
    messagingSenderId: '82640420733',
    projectId: 'better-brain-7231d',
    authDomain: 'better-brain-7231d.firebaseapp.com',
    storageBucket: 'better-brain-7231d.firebasestorage.app',
    measurementId: 'G-CL7MBZ9TWB',
  );
}
